### PR TITLE
ROCM updates

### PR DESCRIPTION
**Pull request by rahulbatra85**
Adds support for ROCm

-Added lowering rules for ROCm and CUDA instead of using runtime information to determine platform

### CODE REVIEW

**Comment by rahulbatra85** [comment]
@hawkinsp  @superbobry  Please review this new PR. Thanks!

**Review by superbobry — APPROVED** [review]

**Comment by hawkinsp** [comment]
Our internal presubmits complain about trailing whitespace in this file.

**Review by hawkinsp — CHANGES_REQUESTED** [review]
Please fix trailing whitespace in all files.

**Review by hawkinsp — APPROVED** [review]
Let's try this version out.

**Review by hawkinsp — APPROVED** [review]

**Comment by rahulbatra85** [comment]
@hawkinsp  @superbobry  Looks like we merged this through other means. Thanks for all the feedback!

Should we close this PR now?

**Comment by hawkinsp** [comment]
Yeah, I merged it with some fixes to make it work.

**Pull request closed without merging**
